# Generated by Django 3.0.7 on 2020-10-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
