# Generated by Django 3.0.7 on 2020-10-16 16:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customeruser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='photo',
            field=models.FileField(blank=True, upload_to=user.models.user_directory),
        ),
    ]
