# Generated by Django 3.0.7 on 2020-10-17 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201016_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='id',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
