# Generated by Django 3.0.7 on 2020-10-18 06:50

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201017_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='photo',
            field=models.FileField(upload_to=user.models.user_directory),
        ),
    ]
