# Generated by Django 3.0.7 on 2020-10-18 08:11

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201018_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='photo',
            field=models.FileField(blank=True, upload_to=user.models.user_directory),
        ),
    ]
