# Generated by Django 3.0.7 on 2020-10-28 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20201018_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_uploaded_on_date', models.DateField(default=datetime.date(2020, 10, 28))),
                ('selled', models.BooleanField(default=False)),
                ('features', models.TextField()),
                ('months_of_product_used', models.IntegerField()),
                ('img1', models.ImageField(blank=True, upload_to=user.models.user_directory)),
                ('img2', models.ImageField(blank=True, upload_to=user.models.user_directory)),
                ('img3', models.ImageField(blank=True, upload_to=user.models.user_directory)),
                ('img4', models.ImageField(blank=True, upload_to=user.models.user_directory)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
