# Generated by Django 3.0.7 on 2020-10-28 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201028_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_uploaded_on_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
