# Generated by Django 3.0.7 on 2020-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201028_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_uploaded_on_date',
            field=models.DateField(),
        ),
    ]
