# Generated by Django 3.0.7 on 2020-10-30 15:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201028_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='dp',
            field=models.ImageField(default='default-user-image.png', upload_to=user.models.user_directory),
        ),
    ]
