# Generated by Django 3.0.7 on 2020-10-30 15:20

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customeruser_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='dp',
            field=models.ImageField(default='images/default-user-image.png', upload_to=user.models.user_directory),
        ),
    ]
