# Generated by Django 3.0.7 on 2020-10-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201030_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='dp',
        ),
    ]
