# Generated by Django 3.0.7 on 2020-10-30 15:25

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_customeruser_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='photo',
            field=models.FileField(default='images/default-user-image.png', upload_to=user.models.user_directory),
        ),
    ]
