# Generated by Django 3.0.7 on 2020-11-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_productcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComments',
        ),
    ]
