# Generated by Django 3.0.7 on 2020-11-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20201102_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_done_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomerUser'),
        ),
    ]
