# Generated by Django 3.0.7 on 2020-11-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20201102_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_carted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Products')),
                ('user_carted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomerUser')),
            ],
        ),
    ]
