# Generated by Django 3.0.7 on 2020-11-09 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20201107_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(default=datetime.datetime.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomerUser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Products')),
            ],
        ),
    ]
