# Generated by Django 3.0.7 on 2020-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_purchasedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
